# Generated by Django 4.2.10 on 2024-03-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='lic_used',
            field=models.IntegerField(default=0),
        ),
    ]
