# Generated by Django 4.2.10 on 2024-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_app', '0004_admin_user_is_active_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
